version: '3'
services:
#  postgres:
#    image: 'postgres:latest'
#    restart: always
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#  nginx:
#    image: 'nginx:latest'
#    restart: always
#    ports:
#      - "8080:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_PASSWORD=postgres_password
    ports:
      - "8081:8081"
